-- Project Hermes: Initial schema for autonomous e-commerce operations
-- Tables: inventory, campaign_logs

CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- ---------------------------------------------------------------------------
-- inventory
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS inventory (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    product_name TEXT NOT NULL,
    stock_level INTEGER NOT NULL CHECK (stock_level >= 0),
    category TEXT NOT NULL,
    reorder_threshold INTEGER NOT NULL DEFAULT 10 CHECK (reorder_threshold >= 0),
    image_url TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_inventory_category ON inventory (category);
CREATE INDEX IF NOT EXISTS idx_inventory_stock_level ON inventory (stock_level);

-- ---------------------------------------------------------------------------
-- campaign_logs
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS campaign_logs (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    campaign_copy TEXT NOT NULL,
    target_audience TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'draft'
        CHECK (status IN ('draft', 'pending_review', 'approved', 'sent', 'archived')),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_campaign_logs_status ON campaign_logs (status);

-- ---------------------------------------------------------------------------
-- Mock boutique inventory (5 products)
-- ---------------------------------------------------------------------------
INSERT INTO inventory (product_name, stock_level, category, reorder_threshold, image_url)
VALUES
    (
        'Celestial Silk Scarf — Midnight Constellation',
        142,
        'Accessories',
        25,
        'https://images.unsplash.com/photo-1601924994987-69e26d50dc26?auto=format&fit=crop&w=200&h=200&q=80'
    ),
    (
        'Artisan Ceramic Pour-Over Set',
        87,
        'Home & Kitchen',
        15,
        'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?auto=format&fit=crop&w=200&h=200&q=80'
    ),
    (
        'Hand-Poured Amber & Vetiver Candle',
        210,
        'Home Fragrance',
        40,
        'https://images.unsplash.com/photo-1603006905003-be475563bc59?auto=format&fit=crop&w=200&h=200&q=80'
    ),
    (
        'Organic Linen Lounge Set — Sand',
        34,
        'Apparel',
        20,
        'https://images.unsplash.com/photo-1523381210434-271e8be1f52b?auto=format&fit=crop&w=200&h=200&q=80'
    ),
    (
        'Recycled Brass Statement Earrings',
        156,
        'Jewelry',
        30,
        'https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?auto=format&fit=crop&w=200&h=200&q=80'
    );

-- Seed an empty draft campaign log for reference
INSERT INTO campaign_logs (campaign_copy, target_audience, status)
VALUES (
    'Placeholder — generated by Hermes Growth Marketer agent.',
    'Boutique lifestyle enthusiasts, ages 25–45',
    'draft'
);
